# ==========================================
# MODUL 1: AUTENTIKASI (M1)
# ==========================================

# 1. LOGIN API (Dapatkan Token)
# Jalankan ini pertama kali, lalu copy "access_token" dari hasil responsnya.
POST http://127.0.0.1:8000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "ali@smpn4palu.sch.id",
    "password": "password123"
}

###

# 2. CEK PROFIL ME (Butuh Token)
# Ganti <TOKEN_DI_SINI> dengan token asli dari proses login
GET http://127.0.0.1:8000/api/auth/me
Accept: application/json
Authorization: Bearer <TOKEN_DI_SINI>

###

# 3. LOGOUT API (Hapus Token)
# Jika ini dijalankan, token akan hangus dan kamu harus login ulang
POST http://127.0.0.1:8000/api/auth/logout
Accept: application/json
Authorization: Bearer <TOKEN_DI_SINI>

###

# ==========================================
# MODUL 2: DATA GURU (M2)
# ==========================================

# 4. TAMBAH DATA GURU
# Pastikan user_id (3) belum ada di tabel gurus sebelumnya
POST http://127.0.0.1:8000/api/guru
Accept: application/json
Content-Type: application/json
Authorization: Bearer <TOKEN_DI_SINI>

{
    "user_id": 3,
    "nip": "198501012010011001",
    "nama_lengkap": "Diyowansyah",
    "gelar_depan": null,
    "gelar_belakang": "S.Pd.",
    "jenis_kelamin": "L",
    "tempat_lahir": "Palu",
    "tanggal_lahir": "1985-05-15",
    "agama": "Islam",
    "no_hp": "081234567890",
    "alamat": "Jl. Pendidikan No. 12, Kota Palu"
}

###

# 5. LIHAT SEMUA DATA GURU
GET http://127.0.0.1:8000/api/guru
Accept: application/json
Authorization: Bearer <TOKEN_DI_SINI>
